#we use java
language: java
#we add the java development kit (jdk)

services:
#Linking Travis CI and Docker
- docker
addons:
  sonarcloud:
    organization: "ecabs"
    token:
      secure: "$SONAR_TOKEN" # encrypted value of your token
before_install:
 - docker login --username Kyrsor --password d05b79e8-d00f-4c44-a000-76797f3c71c1 registry.heroku.com
 - chmod +x ./mvnw
 - chmod +x mvnw
 - chmod +x producer/mvnw
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - cd producer
  - docker build -f Dockerfile -t producer:1.0 .
  - docker build -t registry.heroku.com/producer-ecabs/web .
  - docker push registry.heroku.com/producer-ecabs/web
  - heroku container:release web -a producer-ecabs
  - cd ..
  - cd consumer
  - docker build -f Dockerfile -t consumer:1.0 .
  - docker build -t registry.heroku.com/consumer-ecabs/web .
  - docker push registry.heroku.com/consumer-ecabs/web
  - heroku container:release web -a consumer-ecabs
