#we use java
language: java
#we add the java development kit (jdk)
deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_API_KEY"
services:
#Linking Travis CI and Docker
- docker
addons:
  sonarcloud:
    organization: "ecabs"
    token:
      secure: "$SONAR_TOKEN" # encrypted value of your token
before_install:
 - docker login --username=_ --password=$(heroku auth:token) registry.heroku.com
 - chmod 777 ./mvnw
script:
  # the following commandd- cd producer
  - docker build -f  etc/services/producer/Dockerfile -t producer:1.0 .
  - docker build -t registry.heroku.com/producer-ecabs/web .
  - docker push registry.heroku.com/producer-ecabs/web
  - heroku container:release web -a producer-ecabs
  - cd ..
  - cd consumer
  - docker build -f Dockerfile -t consumer:1.0 .
  - docker build -t registry.heroku.com/consumer-ecabs/web .
  - docker push registry.heroku.com/consumer-ecabs/web
  - heroku container:release web -a consumer-ecabs
